# Default values for awx
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

web:
  image:
    repository: ansible/awx_web
    tag: 8.0.0
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: "1"
    #  memory: "1Gi"
    # requests:
    #  cpu: "1"
    #  memory: "1Gi"
  nodeSelector: {}
  tolerations: []
  affinity: {}

task:
  image:
    repository: ansible/awx_task
    tag: 8.0.0
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: "1.5"
    #  memory: "2Gi"
    # requests:
    #  cpu: "1.5"
    #  memory: "2Gi"
  nodeSelector: {}
  tolerations: []
  affinity: {}

secret_key: awxsecret
default_admin_user: admin
default_admin_password: password

extraConfiguration: |-
  # INSIGHTS_URL_BASE = "https://example.org"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  # whether the default backend for this ingress should route to the awx service
  defaultBackend: true
  # Used to create an Ingress record.
  hosts:
    - chart-example.local
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls: []
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

# Chart values https://github.com/helm/charts/blob/master/stable/memcached/values.yaml
memcached:
  enabled: true

# Chart values https://github.com/helm/charts/blob/master/stable/rabbitmq/values.yaml
rabbitmq:
  enabled: true
  rabbitmq:
    username: admin
    password: amqpassword
    # loadDefinition:
    #   enabled: true
    #   secretName: rabbitmq-load-definition
    ## Configution file content https://www.rabbitmq.com/configure.html#configuration-files
    extraConfiguration: |-
      default_vhost = awx

# Chart values https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml
postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 9.6
  postgresqlUsername: awx
  postgresqlPassword: pgpassword
  postgresqlDatabase: awx
  persistence:
    enabled: true
    # size: 50Gi
  # resources: {}
  metrics:
    enabled: false
